export const CREATE_CARD = 'CREATE_CARD'
export const SELECT_CARD = 'SELECT_CARD'
export const SELECT_ROW = 'SELECT_ROW'
export const ADD_ROW = 'ADD_ROW'
export const UPDATE_POSITION = 'UPDATE_POSITION'
