export const ADD_ROW = 'ADD_ROW'
export const CREATE_TABLE = 'CREATE_TABLE'
export const MOVE_UP = 'MOVE_UP'
export const REMOVE_ROW = 'REMOVE_ROW'
export const REMOVE_TABLE = 'REMOVE_TABLE'
export const SELECT_ROW = 'SELECT_ROW'
export const SELECT_TABLE = 'SELECT_TABLE'
export const UPDATE_POSITION = 'UPDATE_POSITION'
